[features]
seeds = false
skip-lint = false
[programs.localnet]
lending_protocol = "J57zpbkxpJPVRvvvHZ9a7RzRTPAJ1LAcUmE4sK7ZBVqa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src && cp target/idl/lending_protocol.json app/src/idl.json"
deploy-local = "anchor build && anchor run copy-idl && anchor deploy --provider.cluster localnet"