[features]
seeds = false
skip-lint = false
[programs.localnet]
lending_protocol = "7VCF7Hziuyyq9t4q3C2HgTdPGMqn3CiQDSgFKvECEMcH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src && cp target/idl/lendingprotocol.json app/src/idl.json"
deploy-local = "anchor build && anchor deploy && anchor run copy-idl"